# Generated by Django 5.2.14 on 2026-05-13 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='nombre_usuario',
            field=models.CharField(default='default_user', max_length=30),
        ),
    ]
